/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as CursosSlugLicaoMLRouteImport } from './routes/cursos.$slug.licao.$m.$l'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugLicaoMLRoute = CursosSlugLicaoMLRouteImport.update({
  id: '/licao/$m/$l',
  path: '/licao/$m/$l',
  getParentRoute: () => CursosSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/playground': typeof PlaygroundRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/cursos/$slug': typeof CursosSlugRouteWithChildren
  '/cursos/': typeof CursosIndexRoute
  '/cursos/$slug/licao/$m/$l': typeof CursosSlugLicaoMLRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/playground': typeof PlaygroundRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/cursos/$slug': typeof CursosSlugRouteWithChildren
  '/cursos': typeof CursosIndexRoute
  '/cursos/$slug/licao/$m/$l': typeof CursosSlugLicaoMLRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/playground': typeof PlaygroundRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/cursos/$slug': typeof CursosSlugRouteWithChildren
  '/cursos/': typeof CursosIndexRoute
  '/cursos/$slug/licao/$m/$l': typeof CursosSlugLicaoMLRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/playground'
    | '/painel'
    | '/cursos/$slug'
    | '/cursos/'
    | '/cursos/$slug/licao/$m/$l'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/playground'
    | '/painel'
    | '/cursos/$slug'
    | '/cursos'
    | '/cursos/$slug/licao/$m/$l'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/playground'
    | '/_authenticated/painel'
    | '/cursos/$slug'
    | '/cursos/'
    | '/cursos/$slug/licao/$m/$l'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  PlaygroundRoute: typeof PlaygroundRoute
  CursosSlugRoute: typeof CursosSlugRouteWithChildren
  CursosIndexRoute: typeof CursosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug/licao/$m/$l': {
      id: '/cursos/$slug/licao/$m/$l'
      path: '/licao/$m/$l'
      fullPath: '/cursos/$slug/licao/$m/$l'
      preLoaderRoute: typeof CursosSlugLicaoMLRouteImport
      parentRoute: typeof CursosSlugRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CursosSlugRouteChildren {
  CursosSlugLicaoMLRoute: typeof CursosSlugLicaoMLRoute
}

const CursosSlugRouteChildren: CursosSlugRouteChildren = {
  CursosSlugLicaoMLRoute: CursosSlugLicaoMLRoute,
}

const CursosSlugRouteWithChildren = CursosSlugRoute._addFileChildren(
  CursosSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
  PlaygroundRoute: PlaygroundRoute,
  CursosSlugRoute: CursosSlugRouteWithChildren,
  CursosIndexRoute: CursosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
